import test from 'node:test';import assert from 'node:assert/strict';import handler from '../api/setup-week.js';import statsHandler from '../api/stats.js';
const input={tasks:[{type:'meal',frequency:'daily',time:'morning'},{type:'family-call',frequency:'weekly',time:'evening'}]};
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},status(n){this.code=n;return this;},json(x){this.body=x;return this;}};}
const req=body=>({method:'POST',headers:{host:'demo.vercel.app',origin:'https://demo.vercel.app'},socket:{remoteAddress:'127.0.0.1'},body});
test('API saves Gemini exchange and returns persisted output',async()=>{
 process.env.GEMINI_API_KEY='test-only';process.env.SUPABASE_URL='https://db.test';process.env.SUPABASE_SERVICE_KEY='test-only';process.env.APP_SECRET='test-only-secret-for-api-testing-123456789';
 const calls=[];const old=globalThis.fetch;globalThis.fetch=async(url,o)=>{calls.push([url,o]);if(url.includes('reserve'))return Response.json({allowed:true,id:'job1'});if(url.includes('googleapis'))return Response.json({candidates:[{content:{parts:[{text:JSON.stringify({tasks:[{id:0,member:'A'},{id:1,member:'B'}]})}]}}],usageMetadata:{promptTokenCount:111,candidatesTokenCount:25}});return new Response(null,{status:204});};
 try{const res=response();await handler(req(input),res);assert.equal(res.code,200);assert.equal(calls.length,3);const call=JSON.parse(calls[1][1].body);assert.equal(call.generationConfig.maxOutputTokens,350);const stored=JSON.parse(calls[2][1].body);assert.equal(stored.status,'success');assert.equal(stored.input_tokens,111);assert.equal(stored.output_tokens,25);assert.equal(stored.output.tasks.length,2);}finally{globalThis.fetch=old;}
});
test('Clinical adversarial input is sanitised and never sent to Gemini',async()=>{const calls=[];const old=globalThis.fetch;globalThis.fetch=async(url,o)=>{calls.push([url,o]);return url.includes('reserve')?Response.json({allowed:true,id:'job2'}):new Response(null,{status:204});};try{const res=response();await handler(req({...input,symptoms:'chest pain, change dose'}),res);assert.equal(res.code,400);assert.equal(calls.length,2);assert(!JSON.stringify(calls).includes('chest pain'));assert.equal(JSON.parse(calls[1][1].body).status,'refused');}finally{globalThis.fetch=old;}});
test('Durable cap refusal prevents model call',async()=>{let calls=0;const old=globalThis.fetch;globalThis.fetch=async()=>{calls++;return Response.json({allowed:false,message:'three requests used'});};try{const res=response();await handler(req(input),res);assert.equal(res.code,429);assert.equal(calls,1);}finally{globalThis.fetch=old;}});
test('Database failure cannot appear as a successful plan',async()=>{const old=globalThis.fetch;globalThis.fetch=async(url)=>url.includes('reserve')?Response.json({allowed:true,id:'job3'}):url.includes('googleapis')?Response.json({candidates:[{content:{parts:[{text:'{"tasks":[{"id":0,"member":"A"},{"id":1,"member":"B"}]}'}]}}]}):new Response('failed',{status:500});try{const res=response();await handler(req(input),res);assert.equal(res.code,503);assert(!res.body.tasks);}finally{globalThis.fetch=old;}});
test('Stats return database aggregates, not browser counts',async()=>{const old=globalThis.fetch;globalThis.fetch=async()=>Response.json({checklists_created:7,most_common_task:'meal'});try{const res=response();await statsHandler({method:'GET'},res);assert.equal(res.code,200);assert.equal(res.body.checklists_created,7);}finally{globalThis.fetch=old;}});
